set_property -dict { PACKAGE_PIN V27 IOSTANDARD LVCMOS33 } [get_ports { gpio0 }]; #JD[0]
set_property -dict { PACKAGE_PIN Y30 IOSTANDARD LVCMOS33 } [get_ports { gpio1 }]; #JD[1]
set_property -dict { PACKAGE_PIN V24 IOSTANDARD LVCMOS33 } [get_ports { gpio2 }]; #JD[2]
set_property -dict { PACKAGE_PIN W22 IOSTANDARD LVCMOS33 } [get_ports { gpio3 }]; #JD[3]
set_property -dict { PACKAGE_PIN U24 IOSTANDARD LVCMOS33 } [get_ports { gpio4 }]; #JD[4]
